import SwiftUI

struct AllAssets {
    static let assets: [String] = [
        "air", "alas bedak", "alkitab", "ambil", "ambulance", "apa",
        "api", "astronot", "awas", "ayam goreng",
        "ayam", "babi", "baca", "bagaimana", "baju",
        "bak mandi", "ball", "balon udara", "balon", "bantal", "batu",
        "belalang", "berat", "besar", "bidan",
        "bintang", "bis", "bola", "bolpoin",
        "botol", "bowling", "buah buahan", "buang", "buka", "buku",
        "bulan", "bumi", "bunga", "burung", "capung", "celana panjang",
        "celana pendek", "cermin", "coklat", "crayon", "cuci tangan", "dan", "delete", "deodoran", "di atas", "di bawah", "di dalam", "di luar", "di samping", "di", "dia",
        "dimana", "dingin", "dokter bedah", "dokter",
        "drum", "gajah", "gambar", "garam", "garpu",
        "gelas air", "gunting 1", "gunting", "guru", "handuk", "hanger",
        "helikopter", "hiu", "home", "hujan",
        "ibu", "ikan", "iya", "jagung",
        "jaket", "jam", "jerapah", "kacamata", "kalender", "kalkulator",
        "kamera", "kamu", "kaos kaki", "kapal", "kapan", "kardus",
        "kartu atm", "kasur", "ke", "kecil", "kepiting", "keran", "keranjang", "keras", "kereta", "kertas 1", "kertas", "kita", "kodok", "koki", "kolam renang",
        "komputer", "kontraktor", "korek", "kotak p3k",
        "kotak pensil", "ktp", "kuas", "kucing", "kuda",
        "kue kering", "kue", "kunci", "kupu kupu", "kura kura", "kursi roda",
        "kursi", "lampu 1", "lampu lalu lintas", "lampu",
        "layang layang", "lebah", "lem", "lemari",
        "lilin", "lipstik", "lotion", "makan", "mandi", "manis",
        "map", "masukkan", "matahari", "mau", "meja belajar", "meja",
        "mesin cuci", "mie", "minum", "mobil polisi", "mobil", "monyet", "mood tracker", "motor", "mug", "musik", "nasi", "nelayan", "obat", "odol pasta gigi", "odol sikat gigi",
        "ombak", "panas", "papan tulis", "paus",
        "pelari", "pelukis", "pemadam kebakaran", "pemain basket", "penggaris",
        "penghapus", "pensil warna", "pensil", "pesawat", "petani", "peternak",
        "piring", "plester", "pohon", "polisi",
        "potong", "print", "puding", "putar",
        "rautan", "resleting", "rok", "roti", "rumah", "sabun",
        "sandal", "saya", "selesai 1", "selesai", "semangka", "semut",
        "sendok", "sepatu", "sepeda", "setrika", "settings", "shampo", "shower", "siapa", "sikat gigi",
        "sikat", "silet", "singa", "sisir", "sofa", "sosis",
        "spons cuci", "stabilo", "suka", "sup", "surat", "sushi",
        "suster", "susu", "sweater", "tas", "teh", "televisi", "telur", "tempat sampah", "termometer", "tidak mau", "tidak suka", "tidak", "timbangan", "tisu", "toilet",
        "tolong", "topi koboi", "trash", "troli",
        "truk", "tukang pos", "tulis", "tutup", "uang",
        "ular", "warnai"
    ]
}
